# Generated by Django 5.1.4 on 2024-12-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction', '0003_rename_uploaded_at_geotaggedimage_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geotaggedimage',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='crop_name',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='district',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='farmer_name',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='note',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='saplings',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='tahsil',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='time',
        ),
        migrations.RemoveField(
            model_name='geotaggedimage',
            name='village',
        ),
        migrations.AddField(
            model_name='geotaggedimage',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
